const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const ts=require(require.resolve('typescript',{paths:[path.join(__dirname,'../apps/web')]}));
function load(relative,imports,globals={}){const filename=path.join(__dirname,'..',relative);const output=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};vm.runInNewContext(output,{module,exports:module.exports,require:name=>{if(!(name in imports))throw new Error(`Unexpected import: ${name}`);return imports[name];},Date,Intl,Map,Set,URL,URLSearchParams,Request,Response,Headers,AbortSignal,AbortController,Buffer,TextDecoder,setTimeout,clearTimeout,process:{env:{}},...globals},{filename});return module.exports;}
const sources=import('../packages/domain/bia-sources.js');const domain=import('../packages/domain/bia.js');const commercial=import('../packages/domain/commercial-analysis.js');
const linkedom=require(require.resolve('linkedom',{paths:[path.join(__dirname,'../apps/web')]}));
async function parser(fetch=()=>{throw new Error('Unexpected network')}){return load('apps/web/lib/bia/page-source.ts',{'server-only':{},linkedom,'@oraculo/domain/operations.js':await import('../packages/domain/operations.js'),'@oraculo/domain/bia-sources.js':await sources,'@oraculo/domain/bia.js':await domain,'../auth/session':{ACCESS_COOKIE:'oraculo_access_token',REFRESH_COOKIE:'oraculo_refresh_token'}},{fetch});}
const html='<html><body><aside>SEGREDO OUTRA ABA 999</aside><main class="workspace"><h1>Devoluções</h1><div class="metric"><span class="label">Devoluções abertas</span><strong>42</strong><small>Solicitações, não perdas</small></div><div hidden>SEGREDO OCULTO 888</div><script>SEGREDO RSC 777</script><form><input type="hidden" value="TOKEN-SECRETO"><input type="password" value="SENHA-SECRETA"></form><section><h2>Produtos</h2><table><thead><tr><th><button>SKU</button></th><th><button>Unidades</button></th></tr></thead><tbody><tr><td>1</td><td>2</td></tr><tr><td>10</td><td>90</td></tr></tbody></table></section><p>Estorno pode estar estimado pela nota fiscal.</p></main></body></html>';
async function across(allowed){let reads=[];let selections=0;const tabs=load('apps/web/lib/auth/tabs.ts',{});const api=load('apps/web/lib/bia/oraculo.ts',{'server-only':{},'@oraculo/domain/bia-sources.js':await sources,'@oraculo/domain/bia.js':await domain,'@oraculo/domain/commercial-analysis.js':await commercial,'../auth/access':{canAccessRequest:async(_,tab)=>allowed.includes(tab),isMaster:()=>false},'../auth/tabs':tabs,'../operation-context':{getRequestOperation:async()=> 'giracasa'},'./page-source':{readBiaPage:async(_,id,operation,params)=>{reads.push({id,operation,params:params.toString()});return{sourceId:id,label:(await sources).biaSourceById(id).label,href:`/${id}?${params}`,facts:[{id:`${id}:0`,kind:'metric',label:'Devoluções abertas',value:'42'}],notices:[],filters:[]};}},'./evidence-selection':{rankSourceFacts:(_,facts)=>facts,selectBiaEvidence:async(_,facts)=>{selections++;return{facts,local:false};}}});return{reads,get selections(){return selections;},ask:(questions)=>api.answerBiaAcrossOraculo(new Request('https://oraculo.oliverhome.com.br'),{id:'real'},questions,'2026-10-02',new AbortController().signal)};}

test('cada aba e subfonte herda uma permissão existente; todas as abas têm cobertura',async()=>{const{BIA_SOURCES}=await sources;const tabs=load('apps/web/lib/auth/tabs.ts',{});for(const source of BIA_SOURCES)assert.ok(tabs.isTabKey(source.tab),source.id);for(const tab of tabs.TABS.filter(tab=>tab.key!=='bia'))assert.ok(BIA_SOURCES.some(source=>source.tab===tab.key),tab.key);assert.equal(new Set(BIA_SOURCES.map(s=>s.id)).size,BIA_SOURCES.length);});
test('fontes específicas não viram vendas ou outro estoque; assuntos mistos conservam todos os gates',async()=>{const{resolveBiaSources:r}=await sources;assert.deepEqual(r('Quantidade de devoluções Shopee ontem'),['devolucoes']);assert.deepEqual(r('Estoque da Shopee'),['shopee-estoque']);assert.deepEqual(new Set(r('RH e Ads')),new Set(['rh','ads']));assert.deepEqual(new Set(r('Faturamento e devoluções')),new Set(['analise-comercial','devolucoes']));assert.deepEqual(r('E a quantidade?', ['devolucoes']),['devolucoes']);});
test('RH negado não lê página nem chama o modelo, mesmo com B.ia/comercial liberadas',async()=>{const api=await across(['bia','analise-comercial']);const reply=await api.ask(['Quanto é a folha do RH?']);assert.match(reply.text,/não estão liberados/);assert.equal(reply.source,undefined);assert.equal(reply.metrics,undefined);assert.equal(api.reads.length,0);assert.equal(api.selections,0);});
test('pergunta com duas fontes bloqueia tudo se qualquer uma não está liberada',async()=>{const api=await across(['bia','ads']);const reply=await api.ask(['Compare RH e Ads']);assert.match(reply.text,/RH.*não estão liberados/);assert.equal(api.reads.length,0);assert.equal(api.selections,0);});
test('usuário sem Análise Comercial pode consultar Devoluções liberadas, com datas/operação exatas',async()=>{const api=await across(['bia','devolucoes']);const reply=await api.ask(['Qual a quantidade de devoluções de ontem?']);assert.equal(reply.metrics[0].value,'42');assert.equal(api.reads[0].id,'devolucoes');assert.equal(api.reads[0].operation,'giracasa');assert.equal(api.reads[0].params,'inicio=2026-10-01&fim=2026-10-01');assert.match(reply.source.href,/devolucoes/);});
test('revogação e seguimento verificam a permissão da fonte novamente',async()=>{const api=await across(['bia','ads']);const reply=await api.ask(['Devoluções em setembro','E a quantidade?']);assert.match(reply.text,/não estão liberados/);assert.equal(api.reads.length,0);});
test('filtros não disponíveis e datas futuras nunca são descartados para mostrar outro total',async()=>{for(const question of ['Devoluções sem Shopee','Devoluções Donacor ontem','Devoluções em dezembro de 2026','RH em setembro']){const api=await across(['bia','devolucoes','rh']);const reply=await api.ask([question]);assert.equal(reply.metrics,undefined,question);assert.equal(api.reads.length,0,question);}});
test('HTML extrai apenas o conteúdo da fonte, preserva cabeçalhos e exclui dados escondidos',async()=>{const api=await parser();const data=api.extractPageEvidence(html,'devolucoes','/devolucoes','Quantidade de devoluções');assert.equal(data.facts[0].value,'42');assert.ok(data.facts.some(f=>f.value==='SKU: 1 · Unidades: 2'));assert.ok(!JSON.stringify(data).includes('SEGREDO'));assert.ok(!JSON.stringify(data).includes('TOKEN-SECRETO'));assert.ok(!JSON.stringify(data).includes('SENHA-SECRETA'));});
test('busca SKU exata não reproduz cards globais nem SKU com prefixo semelhante',async()=>{const data=(await parser()).extractPageEvidence(html,'devolucoes','/devolucoes','SKU 1');assert.equal(data.facts.length,1);assert.equal(data.facts[0].value,'SKU: 1 · Unidades: 2');assert.equal(data.facts[0].kind,'row');});
test('transporte só usa GET no caminho auditado, sem redirects/cache ou cookies extras',async()=>{let sent;const api=await parser(async(url,options)=>{sent={url:String(url),options};return new Response(html,{headers:{'Content-Type':'text/html'}});});const request=new Request('https://oraculo.oliverhome.com.br/o/giracasa/bia/responder',{headers:{cookie:'oraculo_access_token=user; oraculo_refresh_token=refresh; oraculo_session_window=window; admin_secret=must-not-travel'}});await api.readBiaPage(request,'devolucoes','giracasa',new URLSearchParams({inicio:'2026-09-01',fim:'2026-09-30'}),new AbortController().signal,'devoluções');assert.match(sent.url,/\/o\/giracasa\/devolucoes\?/);assert.equal(sent.options.method,'GET');assert.equal(sent.options.redirect,'error');assert.equal(sent.options.cache,'no-store');assert.ok(!sent.options.headers.Cookie.includes('admin_secret'));for(const url of ['https://evil.example/o/giracasa/devolucoes','https://oraculo.oliverhome.com.br/o/uberlandia/devolucoes','https://oraculo.oliverhome.com.br/o/giracasa/devolucoes?sql=delete'])assert.throws(()=>api.assertBiaPageRequest(url,'https://oraculo.oliverhome.com.br','giracasa','devolucoes'));assert.throws(()=>api.biaInternalOrigin('https://evil.example'));});
test('página negada, redirecionamento ou sem sessão não expõe dados',async()=>{const api=await parser();assert.throws(()=>api.extractPageEvidence('<main class="workspace">Você não tem acesso à aba RH</main>','rh','/rh','RH'),/BIA_SOURCE_DENIED/);await assert.rejects(api.readBiaPage(new Request('https://oraculo.oliverhome.com.br'),'rh','uberlandia',new URLSearchParams(),new AbortController().signal,'RH'),/BIA_SESSION_REQUIRED/);});
test('nome vem do cadastro e não altera autorização',async()=>{const{biaUserName}=await sources;assert.equal(biaUserName({user_metadata:{full_name:'Juliano Calil',role:'admin'}}),'Juliano Calil');assert.equal(biaUserName({email:'maria@example.test'}),'maria');});

async function selector(responseValue, onRequest = () => {}) {
  return load('apps/web/lib/bia/evidence-selection.ts', {'server-only':{},'@oraculo/domain/bia.js':await domain,'../../app/documentacao/ask':{ollamaConfig:()=>({enabled:true,url:'http://model.internal',model:'local'})}}, {fetch:async(url,options)=>{onRequest(JSON.parse(options.body));return Response.json({response:JSON.stringify(responseValue)});}});
}
test('modelo só seleciona fatos conhecidos, não injeta números, URLs ou campos extras',async()=>{
  const facts=[{id:'rh:0',kind:'metric',label:'Total',value:'42'},{id:'rh:1',kind:'note',label:'Fonte',value:'Informação verificada'}];
  for(const invalid of [{ids:['inventado']},{ids:['rh:1'],text:'999 milhões https://evil.test'},null,{ids:[]}]){
    const result=await(await selector(invalid)).selectBiaEvidence('Qual o total?',facts,new AbortController().signal);
    assert.equal(result.local,false);assert.equal(result.facts[0].value,'42');assert.ok(!JSON.stringify(result).includes('evil'));
  }
  const valid=await(await selector({ids:['rh:1']})).selectBiaEvidence('Qual o total?',facts,new AbortController().signal);
  assert.equal(valid.local,true);assert.equal(valid.facts[0].id,'rh:0');
});
test('identificadores pessoais da pergunta e dos fatos não vão para inferência',async()=>{
  let body;const api=await selector({ids:['rh:0']},value=>body=value);
  await api.selectBiaEvidence('CPF 123.456.789-00 maria@example.test',[{id:'rh:0',kind:'note',label:'maria@example.test',value:'123.456.789-00'}],new AbortController().signal);
  assert.ok(!body.prompt.includes('123.456.789-00'));assert.ok(!body.prompt.includes('maria@example.test'));
});
test('campos de ações POST nunca aparecem como filtros da consulta',async()=>{
  const data=(await parser()).extractPageEvidence('<main class="workspace"><form method="post"><label><span>Salário</span><input name="salario" value="12345"></label></form><form method="get"><label><span>Início</span><input name="inicio" value="2026-10-01"></label></form></main>','rh','/rh','RH');
  assert.equal(data.filters.length,1);assert.match(data.filters[0],/Início/);assert.ok(!JSON.stringify(data.filters).includes('12345'));
});
test('permissões reais preservam abas restritas, operação e administração',async()=>{
  const tabs=load('apps/web/lib/auth/tabs.ts',{});
  const access=load('apps/web/lib/auth/access.ts',{'next/navigation':{redirect(){throw Error('redirect');}},'../operation-status':{operationIsReady:()=>true},'../operation-context':{getRequestOperation:async()=> 'giracasa'},'./path-tabs':{tabForPath:()=>null},'./session':{readEnvValue:()=>undefined,requireCurrentUser:async()=>null},'./tabs':tabs},{process:{env:{NODE_ENV:'production'}}});
  const user={id:'ordinary',email:'user@example.test',oraculo_operation:'giracasa',app_metadata:{tabs:['bia','rh','parametros','usuarios','full'],restricted_tabs:[]}};
  assert.equal(await access.canAccessRequest(user,'rh'),true);assert.equal(await access.canAccessRequest(user,'ads'),false);
  assert.equal(await access.canAccessRequest(user,'parametros'),false);assert.equal(access.isMaster(user),false);assert.equal(await access.canAccessRequest(user,'full'),false);
  assert.equal(await access.canAccessRequest({...user,app_metadata:{...user.app_metadata,restricted_tabs:['parametros']}},'parametros'),true);
  assert.equal(await access.canAccessRequest({...user,oraculo_operation_allowed:false},'rh'),false);
});
test('fonte com falha visível não produz números de fallback',async()=>{
  const api=await parser();assert.throws(()=>api.extractPageEvidence('<main class="workspace"><p>Não foi possível carregar os dados.</p><div class="metric"><span>Total</span><strong>0</strong></div></main>','devolucoes','/devolucoes','Total'),/BIA_SOURCE_UNAVAILABLE/);
});

test('Usuários exige administrador mesmo com uma concessão antiga dessa aba',async()=>{const api=await across(['bia','usuarios']);const reply=await api.ask(['Quais usuários estão cadastrados?']);assert.match(reply.text,/não estão liberados/);assert.equal(api.reads.length,0);});
test('sugestão de ranking continua na receita comercial com período, não em uma tela sem filtro',async()=>{assert.deepEqual((await sources).resolveBiaSources('Top 10 produtos mais vendidos da Shopee no mês passado'),['analise-comercial']);});
