-- Base da integração direta com o TikTok Shop (loja Donacor), no mesmo padrão
-- da Shopee direta: tabelas de credencial service_role-only + tabelas de
-- pedidos/itens alimentadas por edge function (tiktok-sync), com log em
-- tiktok_sync_runs.
--
-- Papel da fonte (mesma decisão da Shopee, 2026-07-13): o Olist segue sendo a
-- verdade da receita; o TikTok direto entra como camada de double-check e de
-- detalhe por SKU/financeiro que o Olist não tem.
--
-- Segurança: app_secret/access_token/refresh_token ficam em tabelas com RLS e
-- acesso SOMENTE service_role. Nunca aparecem em página.

-- 1) Credenciais -------------------------------------------------------------

create table if not exists public.tiktok_app_config (
  id bigint generated by default as identity primary key,
  app_key text not null unique,
  app_secret text not null,
  service_id text,          -- id do "serviço personalizado" no Partner Center (gera o link de autorização)
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Uma linha por autorização de seller (a Donacor gera uma). O refresh_token do
-- TikTok é de longa duração; o access_token dura ~7 dias e é renovado pelo
-- tiktok-sync (único renovador, mesma regra de ouro da Shopee).
create table if not exists public.tiktok_tokens (
  id bigint generated by default as identity primary key,
  app_key text not null,
  open_id text not null unique,
  seller_name text,
  seller_base_region text,
  access_token text,
  refresh_token text,
  access_token_expires_at timestamptz,
  refresh_token_expires_at timestamptz,
  raw_response jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Lojas autorizadas (retorno de /authorization/202309/shops). O `cipher` é
-- obrigatório em toda chamada de API no escopo da loja.
create table if not exists public.tiktok_shops (
  id bigint generated by default as identity primary key,
  shop_id text not null unique,
  open_id text not null,
  shop_name text,
  region text,
  seller_type text,
  cipher text,
  shop_code text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.tiktok_app_config enable row level security;
alter table public.tiktok_tokens enable row level security;
alter table public.tiktok_shops enable row level security;

revoke all on table public.tiktok_app_config from public, anon, authenticated;
revoke all on table public.tiktok_tokens from public, anon, authenticated;
revoke all on table public.tiktok_shops from public, anon, authenticated;

grant all on table public.tiktok_app_config to service_role;
grant all on table public.tiktok_tokens to service_role;
grant all on table public.tiktok_shops to service_role;

-- 2) Pedidos -----------------------------------------------------------------

create table if not exists public.tiktok_orders (
  id text primary key,               -- `${shop_id}-${order_id}`
  shop_id text not null,
  shop_name text,
  order_id text not null,
  order_status text,
  create_time timestamptz,
  update_time timestamptz,
  paid_time timestamptz,
  total_amount numeric,              -- payment.total_amount
  sub_total numeric,                 -- payment.sub_total (produtos após desconto)
  platform_discount numeric,         -- payment.platform_discount
  seller_discount numeric,           -- payment.seller_discount
  shipping_fee numeric,              -- payment.shipping_fee (pago pelo comprador)
  currency text,
  buyer_user_id text,
  buyer_email text,
  recipient_name text,
  recipient_phone text,
  recipient_city text,
  recipient_state text,
  fulfillment_type text,
  delivery_option_name text,
  raw_json jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now()
);

create unique index if not exists tiktok_orders_shop_order_idx
  on public.tiktok_orders (shop_id, order_id);
create index if not exists tiktok_orders_create_time_idx
  on public.tiktok_orders (create_time desc);
create index if not exists tiktok_orders_status_idx
  on public.tiktok_orders (order_status);

-- No TikTok cada line_item é 1 unidade; agregamos por SKU no upsert
-- (quantity = nº de line_items daquele SKU no pedido).
create table if not exists public.tiktok_order_items (
  id text primary key,               -- `${shop_id}-${order_id}-${sku_id}`
  order_id text not null references public.tiktok_orders (id) on delete cascade,
  shop_id text not null,
  tiktok_order_id text not null,
  product_id text,
  product_name text,
  sku_id text,
  sku_name text,
  seller_sku text,
  quantity integer not null default 0,
  original_price numeric,            -- unitário
  sale_price numeric,                -- unitário após descontos
  raw_json jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now()
);

create index if not exists tiktok_order_items_order_id_idx
  on public.tiktok_order_items (order_id);
create index if not exists tiktok_order_items_seller_sku_idx
  on public.tiktok_order_items (seller_sku);

create table if not exists public.tiktok_sync_runs (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null check (status in ('running', 'success', 'failed', 'skipped')),
  records_fetched integer not null default 0,
  records_upserted integer not null default 0,
  error_message text,
  meta jsonb not null default '{}'::jsonb
);

create index if not exists tiktok_sync_runs_source_started_at_idx
  on public.tiktok_sync_runs (source, started_at desc);

alter table public.tiktok_orders enable row level security;
alter table public.tiktok_order_items enable row level security;
alter table public.tiktok_sync_runs enable row level security;

revoke all on table public.tiktok_orders from public, anon, authenticated;
revoke all on table public.tiktok_order_items from public, anon, authenticated;
revoke all on table public.tiktok_sync_runs from public, anon, authenticated;

grant all on table public.tiktok_orders to service_role;
grant all on table public.tiktok_order_items to service_role;
grant all on table public.tiktok_sync_runs to service_role;
