-- Logistica - separacao operacional persistida.
--
-- O fechamento multicanal deixa de existir apenas dentro do estado estatico do
-- n8n: cada execucao vira um documento imutavel, pronto para consulta,
-- reimpressao e auditoria no Oraculo. O worker continua sendo o unico escritor;
-- usuarios autenticados leem sob RLS e toda acao de escrita passa por Server
-- Action depois de assertTabAccess('logistica').

begin;

set local lock_timeout = '5s';
set local statement_timeout = '120s';

create table public.logistica_picking_cursor (
  operation_id text primary key default 'uberlandia'
    check (operation_id = 'uberlandia'),
  last_cursor_end timestamptz,
  last_slot_key text,
  updated_at timestamptz not null default now()
);

create table public.logistica_picking_listas (
  id uuid primary key default gen_random_uuid(),
  operation_id text not null default 'uberlandia'
    check (operation_id = 'uberlandia'),
  kind text not null check (kind in ('official', 'custom')),
  trigger_source text not null
    check (trigger_source in ('schedule', 'refresh_button', 'custom_form')),
  status text not null default 'pending'
    check (status in ('pending', 'syncing', 'processing', 'ready', 'blocked', 'failed')),
  slot_key text,
  cursor_start timestamptz not null,
  cursor_end timestamptz not null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  requested_by uuid,
  requested_by_email text,
  generated_at timestamptz,
  olist_sync_finished_at timestamptz,
  orders_count integer not null default 0 check (orders_count >= 0),
  orders_without_items integer not null default 0 check (orders_without_items >= 0),
  rows_count integer not null default 0 check (rows_count >= 0),
  units_sold numeric not null default 0 check (units_sold >= 0),
  boxes_total numeric not null default 0 check (boxes_total >= 0),
  loose_units_total numeric not null default 0 check (loose_units_total >= 0),
  marketplace_count integer not null default 0 check (marketplace_count >= 0),
  unmapped_count integer not null default 0 check (unmapped_count >= 0),
  whatsapp_status text not null default 'not_requested'
    check (whatsapp_status in ('not_requested', 'pending', 'sent', 'failed')),
  whatsapp_sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint logistica_picking_listas_interval_check
    check (cursor_end > cursor_start and period_end > period_start),
  constraint logistica_picking_listas_custom_window_check
    check (kind <> 'custom' or period_end - period_start <= interval '7 days'),
  constraint logistica_picking_listas_slot_check
    check ((kind = 'official' and slot_key is not null) or (kind = 'custom' and slot_key is null)),
  unique (id, operation_id)
);

create table public.logistica_picking_itens (
  id bigint generated by default as identity primary key,
  operation_id text not null default 'uberlandia'
    check (operation_id = 'uberlandia'),
  lista_id uuid not null,
  position integer not null check (position > 0),
  sku text,
  product text not null,
  description text not null,
  sold_quantity numeric not null check (sold_quantity >= 0),
  boxes numeric not null check (boxes >= 0),
  loose_units numeric not null check (loose_units >= 0),
  created_at timestamptz not null default now(),
  constraint logistica_picking_itens_lista_fk
    foreign key (lista_id, operation_id)
    references public.logistica_picking_listas (id, operation_id)
    on delete cascade,
  unique (lista_id, position)
);

create table public.logistica_picking_impressoes (
  id bigint generated by default as identity primary key,
  operation_id text not null default 'uberlandia'
    check (operation_id = 'uberlandia'),
  lista_id uuid not null,
  printed_by uuid,
  printed_by_email text,
  printed_at timestamptz not null default now(),
  constraint logistica_picking_impressoes_lista_fk
    foreign key (lista_id, operation_id)
    references public.logistica_picking_listas (id, operation_id)
    on delete cascade
);

create unique index logistica_picking_listas_official_slot_uidx
  on public.logistica_picking_listas (operation_id, slot_key)
  where kind = 'official';

create index logistica_picking_listas_history_idx
  on public.logistica_picking_listas (operation_id, created_at desc);

create unique index logistica_picking_listas_one_active_uidx
  on public.logistica_picking_listas (operation_id, kind)
  where status in ('pending', 'syncing', 'processing');

create index logistica_picking_itens_lista_idx
  on public.logistica_picking_itens (lista_id, position);

create index logistica_picking_impressoes_lista_idx
  on public.logistica_picking_impressoes (lista_id, printed_at desc);

alter table public.logistica_picking_cursor enable row level security;
alter table public.logistica_picking_listas enable row level security;
alter table public.logistica_picking_itens enable row level security;
alter table public.logistica_picking_impressoes enable row level security;

-- O gate da interface nao substitui a RLS. A permissao e conferida ao vivo em
-- auth.users para que a revogacao de Logistica tenha efeito mesmo com JWT
-- antigo, seguindo a mesma regra de operacao usada pelo restante do Oraculo.
create or replace function oraculo_private.can_access_operation_tab(
  p_operation text,
  p_tab text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when coalesce(current_setting('request.jwt.claims', true), '') <> ''
      and (current_setting('request.jwt.claims', true)::jsonb->>'role') = 'service_role' then true
    when coalesce(current_setting('request.jwt.claims', true), '') = ''
      and current_setting('role') in ('none', 'postgres', 'service_role') then true
    else exists (
      select 1
      from auth.users u
      join public.oraculo_operations o on o.id = p_operation
      where u.id = auth.uid()
        and (u.banned_until is null or u.banned_until < now())
        and o.enabled
        and case
          when u.raw_app_meta_data ? 'operations' then
            u.raw_app_meta_data->'operations'->p_operation->>'enabled' = 'true'
          else
            p_operation = 'uberlandia'
        end
        and (
          lower(coalesce(u.email, '')) in ('juliano@oliverhome.com.br', 'oliveiros_cardoso@hotmail.com')
          or case
            when u.raw_app_meta_data ? 'operations' then
              coalesce(u.raw_app_meta_data->'operations'->p_operation->'tabs', '[]'::jsonb) ? p_tab
            else
              coalesce(u.raw_app_meta_data->'tabs', '[]'::jsonb) ? p_tab
          end
        )
    )
  end;
$$;

revoke all on function oraculo_private.can_access_operation_tab(text, text) from public, anon;
grant execute on function oraculo_private.can_access_operation_tab(text, text) to authenticated, service_role;

revoke all on public.logistica_picking_cursor from public, anon, authenticated;
revoke all on public.logistica_picking_listas from public, anon, authenticated;
revoke all on public.logistica_picking_itens from public, anon, authenticated;
revoke all on public.logistica_picking_impressoes from public, anon, authenticated;
revoke all on sequence public.logistica_picking_itens_id_seq from public, anon, authenticated;
revoke all on sequence public.logistica_picking_impressoes_id_seq from public, anon, authenticated;

grant all on public.logistica_picking_cursor to service_role;
grant all on public.logistica_picking_listas to service_role;
grant all on public.logistica_picking_itens to service_role;
grant all on public.logistica_picking_impressoes to service_role;
grant all on sequence public.logistica_picking_itens_id_seq to service_role;
grant all on sequence public.logistica_picking_impressoes_id_seq to service_role;

grant select on public.logistica_picking_listas to authenticated;
grant select on public.logistica_picking_itens to authenticated;
grant select on public.logistica_picking_impressoes to authenticated;

create policy logistica_picking_listas_operation_select
  on public.logistica_picking_listas for select to authenticated
  using ((select oraculo_private.can_access_operation_tab('uberlandia', 'logistica')));

create policy logistica_picking_itens_operation_select
  on public.logistica_picking_itens for select to authenticated
  using ((select oraculo_private.can_access_operation_tab('uberlandia', 'logistica')));

create policy logistica_picking_impressoes_operation_select
  on public.logistica_picking_impressoes for select to authenticated
  using ((select oraculo_private.can_access_operation_tab('uberlandia', 'logistica')));

-- Claim atomico: duas chamadas do webhook nunca processam a mesma lista. Um
-- worker abandonado pode ser retomado depois de 20 minutos.
create or replace function public.logistica_picking_claim(p_lista_id uuid)
returns setof public.logistica_picking_listas
language sql
volatile
security invoker
set search_path = public, pg_temp
as $$
  update public.logistica_picking_listas
     set status = 'processing',
         last_error = null,
         updated_at = now()
   where id = p_lista_id
     and (
       status in ('pending', 'failed', 'blocked')
       or (status in ('syncing', 'processing') and updated_at < now() - interval '20 minutes')
     )
  returning *;
$$;

-- Finaliza cabecalho e itens no mesmo commit. O worker entrega o mesmo JSON
-- usado para WhatsApp/CSV; apenas linhas com duas caixas ou mais viram o
-- documento operacional.
create or replace function public.logistica_picking_finalize(
  p_lista_id uuid,
  p_report jsonb,
  p_advance_cursor boolean default false
)
returns setof public.logistica_picking_listas
language plpgsql
volatile
security invoker
set search_path = public, pg_temp
as $$
declare
  target public.logistica_picking_listas%rowtype;
  current_cursor timestamptz;
  printable_rows integer;
  printable_boxes numeric;
  printable_loose_units numeric;
begin
  select * into target
  from public.logistica_picking_listas
  where id = p_lista_id
  for update;

  if not found then
    raise exception 'Lista de separacao nao encontrada.' using errcode = 'P0002';
  end if;

  if coalesce((p_report->>'orders_without_items')::integer, 0) > 0 then
    update public.logistica_picking_listas
       set status = 'blocked',
           orders_count = coalesce((p_report->>'orders_count')::integer, 0),
           orders_without_items = coalesce((p_report->>'orders_without_items')::integer, 0),
           last_error = 'Ha pedidos Olist sem itens; sincronize os detalhes antes de gerar a lista.',
           updated_at = now()
     where id = p_lista_id;
    return query select * from public.logistica_picking_listas where id = p_lista_id;
    return;
  end if;

  delete from public.logistica_picking_itens where lista_id = p_lista_id;

  insert into public.logistica_picking_itens (
    operation_id, lista_id, position, sku, product, description,
    sold_quantity, boxes, loose_units
  )
  select
    target.operation_id,
    target.id,
    row_number() over (
      order by coalesce((entry.value->>'boxes')::numeric, 0) desc,
               coalesce((entry.value->>'loose_units')::numeric, 0) desc,
               coalesce(entry.value->>'sku', ''),
               entry.ordinality
    )::integer,
    nullif(trim(entry.value->>'sku'), ''),
    coalesce(nullif(trim(entry.value->>'product'), ''), 'Produto sem descricao'),
    coalesce(nullif(trim(entry.value->>'description'), ''), 'Produto sem descricao'),
    coalesce((entry.value->>'sold_quantity')::numeric, 0),
    coalesce((entry.value->>'boxes')::numeric, 0),
    coalesce((entry.value->>'loose_units')::numeric, 0)
  from jsonb_array_elements(coalesce(p_report->'rows', '[]'::jsonb))
    with ordinality as entry(value, ordinality)
  where coalesce((entry.value->>'boxes')::numeric, 0) >= 2;

  get diagnostics printable_rows = row_count;

  select coalesce(sum(boxes), 0), coalesce(sum(loose_units), 0)
    into printable_boxes, printable_loose_units
  from public.logistica_picking_itens
  where lista_id = p_lista_id;

  update public.logistica_picking_listas
     set status = 'ready',
         generated_at = now(),
         orders_count = coalesce((p_report->>'orders_count')::integer, 0),
         orders_without_items = 0,
         rows_count = printable_rows,
         units_sold = coalesce((p_report->>'units_sold')::numeric, 0),
         boxes_total = printable_boxes,
         loose_units_total = printable_loose_units,
         marketplace_count = coalesce((p_report->>'marketplace_count')::integer, 0),
         unmapped_count = coalesce((p_report->>'unmapped_count')::integer, 0),
         olist_sync_finished_at = nullif(p_report->>'olist_sync_finished_at', '')::timestamptz,
         last_error = null,
         updated_at = now()
   where id = p_lista_id;

  if p_advance_cursor then
    if target.kind <> 'official' then
      raise exception 'Lista personalizada nao pode avancar o cursor oficial.' using errcode = '22023';
    end if;

    insert into public.logistica_picking_cursor (operation_id)
    values (target.operation_id)
    on conflict (operation_id) do nothing;

    select last_cursor_end into current_cursor
    from public.logistica_picking_cursor
    where operation_id = target.operation_id
    for update;

    if current_cursor is not null and current_cursor <> target.cursor_start then
      raise exception 'Cursor oficial mudou durante a geracao; lista nao publicada.' using errcode = '40001';
    end if;

    update public.logistica_picking_cursor
       set last_cursor_end = target.cursor_end,
           last_slot_key = target.slot_key,
           updated_at = now()
     where operation_id = target.operation_id;
  end if;

  return query select * from public.logistica_picking_listas where id = p_lista_id;
end;
$$;

create or replace function public.logistica_picking_fail(
  p_lista_id uuid,
  p_message text
)
returns setof public.logistica_picking_listas
language sql
volatile
security invoker
set search_path = public, pg_temp
as $$
  update public.logistica_picking_listas
     set status = 'failed',
         last_error = left(coalesce(nullif(trim(p_message), ''), 'Falha desconhecida.'), 1000),
         updated_at = now()
   where id = p_lista_id
  returning *;
$$;

revoke all on function public.logistica_picking_claim(uuid) from public, anon, authenticated;
revoke all on function public.logistica_picking_finalize(uuid, jsonb, boolean) from public, anon, authenticated;
revoke all on function public.logistica_picking_fail(uuid, text) from public, anon, authenticated;
grant execute on function public.logistica_picking_claim(uuid) to service_role;
grant execute on function public.logistica_picking_finalize(uuid, jsonb, boolean) to service_role;
grant execute on function public.logistica_picking_fail(uuid, text) to service_role;

comment on table public.logistica_picking_cursor is
  'Cursor duravel do fechamento oficial de separacao. Somente service_role; listas personalizadas nunca o alteram.';
comment on table public.logistica_picking_listas is
  'Documentos de separacao multicanal gerados pelo worker. Um slot oficial e unico por operacao; listas prontas ficam disponiveis para reimpressao.';
comment on table public.logistica_picking_itens is
  'Linhas congeladas da lista de separacao, ja filtradas para o minimo operacional de duas caixas.';
comment on table public.logistica_picking_impressoes is
  'Auditoria append-only de cliques em Imprimir. O navegador nao informa se a caixa de dialogo foi confirmada ou cancelada.';
comment on function oraculo_private.can_access_operation_tab(text, text) is
  'Confere ao vivo em auth.users se o usuario pode acessar a operacao e a aba informadas; service_role permanece liberada para workers.';
comment on column public.logistica_picking_listas.kind is
  'official usa e avanca o cursor; custom e independente e limitado a sete dias.';
comment on column public.logistica_picking_listas.trigger_source is
  'schedule, refresh_button ou custom_form.';
comment on column public.logistica_picking_listas.status is
  'pending, syncing, processing, ready, blocked ou failed.';
comment on column public.logistica_picking_listas.cursor_start is
  'Inicio exclusivo em olist_orders.first_seen_at.';
comment on column public.logistica_picking_listas.cursor_end is
  'Fim inclusivo em olist_orders.first_seen_at.';
comment on function public.logistica_picking_claim(uuid) is
  'Reserva atomicamente uma lista para um worker service_role; permite recuperar execucoes abandonadas depois de 20 minutos.';
comment on function public.logistica_picking_finalize(uuid, jsonb, boolean) is
  'Persiste o mesmo relatorio usado no WhatsApp/CSV e, quando oficial, avanca o cursor no mesmo commit.';
comment on function public.logistica_picking_fail(uuid, text) is
  'Registra falha operacional limitada a mil caracteres para permitir nova tentativa.';

notify pgrst, 'reload schema';

commit;
