-- Base para trazer o sync Shopee para dentro do Oráculo: tabelas de credencial
-- espelhando o projeto "Espaço de Bicho" (aisbanubvjwxrfjoywpd), onde hoje vivem
-- os tokens das 4 lojas (Donacor/2032705, Jacartta/2038778, Espaço de Bicho/2038777,
-- Oliverhome/2038779).
--
-- Segurança: guardam segredos (partner_key, access_token). RLS ligado e acesso
-- SOMENTE service_role — a edge function do sync usa service_role; nunca ficam
-- legíveis por anon/authenticated. Os tokens não aparecem em nenhuma página.

create table if not exists public.shopee_app_config (
  id bigint generated by default as identity primary key,
  partner_id text not null unique,
  partner_key text not null,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.shopee_shops (
  id bigint generated by default as identity primary key,
  shop_id bigint not null unique,
  partner_id bigint not null,
  shop_name text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.shopee_tokens (
  id bigint generated by default as identity primary key,
  shop_id bigint not null unique,
  partner_id bigint not null,
  access_token text,
  refresh_token text,
  access_token_expires_at timestamptz,
  refresh_token_expires_at timestamptz,
  raw_response jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.shopee_app_config enable row level security;
alter table public.shopee_shops enable row level security;
alter table public.shopee_tokens enable row level security;

revoke all on table public.shopee_app_config from public, anon, authenticated;
revoke all on table public.shopee_shops from public, anon, authenticated;
revoke all on table public.shopee_tokens from public, anon, authenticated;

grant all on table public.shopee_app_config to service_role;
grant all on table public.shopee_shops to service_role;
grant all on table public.shopee_tokens to service_role;
