-- Logística Fase 2 — recebimento e conferência de mercadoria.
--
-- Liga a chegada física ao que já existe em importações: ao iniciar a
-- conferência de uma fatura, os itens esperados são copiados de
-- importacao_itens (quantidade e cartons) e o time do depósito registra o que
-- de fato chegou, item a item, pelo celular. O saldo oficial continua no
-- Olist — aqui fica o REGISTRO da conferência e a divergência apontada; o
-- lançamento de entrada acontece no ERP.
--
-- Referências a importacao_faturas/importacao_itens são soltas (sem FK):
-- as faturas podem ser recarregadas da planilha (origin = 'planilha') e um
-- recebimento já conferido não pode sumir junto.

create table if not exists public.logistica_recebimentos (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  container_number text,
  status text not null default 'em_conferencia'
    check (status in ('aguardando', 'em_conferencia', 'concluido', 'concluido_com_divergencia')),
  observacoes text,
  iniciado_em timestamptz not null default now(),
  iniciado_por text,
  concluido_em timestamptz,
  concluido_por text,
  created_at timestamptz not null default now()
);

create table if not exists public.logistica_recebimento_itens (
  id bigint generated by default as identity primary key,
  recebimento_id uuid not null references public.logistica_recebimentos (id) on delete cascade,
  importacao_item_id bigint,
  descricao text not null,
  sku text,
  qty_esperada numeric,
  cartons_esperados numeric,
  qty_conferida numeric,
  cartons_conferidos numeric,
  divergencia text check (divergencia in ('ok', 'falta', 'sobra', 'avaria')),
  observacao text,
  conferido_em timestamptz,
  conferido_por text,
  created_at timestamptz not null default now()
);

create index if not exists logistica_recebimento_itens_recebimento_idx
  on public.logistica_recebimento_itens (recebimento_id);
create index if not exists logistica_recebimento_itens_sku_idx
  on public.logistica_recebimento_itens (sku) where sku is not null;

alter table public.logistica_recebimentos enable row level security;
alter table public.logistica_recebimento_itens enable row level security;

revoke all on public.logistica_recebimentos from public, anon, authenticated;
revoke all on public.logistica_recebimento_itens from public, anon, authenticated;
grant all on public.logistica_recebimentos to service_role;
grant all on public.logistica_recebimento_itens to service_role;
grant select on public.logistica_recebimentos to authenticated;
grant select on public.logistica_recebimento_itens to authenticated;

drop policy if exists logistica_recebimentos_select on public.logistica_recebimentos;
create policy logistica_recebimentos_select
  on public.logistica_recebimentos for select to authenticated using (true);
drop policy if exists logistica_recebimento_itens_select on public.logistica_recebimento_itens;
create policy logistica_recebimento_itens_select
  on public.logistica_recebimento_itens for select to authenticated using (true);

comment on table public.logistica_recebimentos is
  'Conferência de recebimento de uma fatura de importação (uma por invoice_number). Criada ao iniciar a conferência em /logistica/recebimento; os itens esperados são copiados de importacao_itens naquele momento. Registro operacional do depósito — o lançamento de entrada continua sendo feito no Olist.';
comment on column public.logistica_recebimentos.invoice_number is 'Número da fatura (importacao_faturas.invoice_number). Referência solta: a fatura pode ser recarregada da planilha sem apagar a conferência.';
comment on column public.logistica_recebimentos.status is 'em_conferencia | concluido | concluido_com_divergencia (algum item com falta/sobra/avaria). aguardando reservado para uso futuro.';
comment on column public.logistica_recebimentos.iniciado_por is 'E-mail de quem iniciou a conferência (sessão do Oráculo).';
comment on column public.logistica_recebimentos.concluido_por is 'E-mail de quem concluiu a conferência.';

comment on table public.logistica_recebimento_itens is
  'Itens de uma conferência de recebimento: o esperado (copiado de importacao_itens: quantity, ou cartons × quantity_per_carton) contra o conferido no galpão, com a divergência classificada (ok/falta/sobra/avaria) e o SKU Olist opcional para cruzar com o saldo do ERP.';
comment on column public.logistica_recebimento_itens.importacao_item_id is 'importacao_itens.id de origem (referência solta).';
comment on column public.logistica_recebimento_itens.sku is 'SKU Olist informado na conferência — opcional; quando preenchido permite comparar a entrada com a variação de saldo em olist_stock_items.';
comment on column public.logistica_recebimento_itens.qty_esperada is 'Unidades esperadas: importacao_itens.quantity, ou cartons × quantity_per_carton quando quantity está vazio.';
comment on column public.logistica_recebimento_itens.divergencia is 'ok | falta (chegou menos) | sobra (chegou mais) | avaria (chegou danificado). Sugerida pela tela a partir de esperado × conferido; a pessoa confirma.';

create or replace view public.oraculo_recebimento_progress as
select
  r.id,
  r.invoice_number,
  r.container_number,
  r.status,
  r.iniciado_em,
  r.iniciado_por,
  r.concluido_em,
  r.concluido_por,
  count(i.id) as total_itens,
  count(i.id) filter (where i.conferido_em is not null) as itens_conferidos,
  count(i.id) filter (where i.divergencia in ('falta', 'sobra', 'avaria')) as itens_divergentes,
  coalesce(sum(i.qty_esperada), 0) as qty_esperada_total,
  coalesce(sum(i.qty_conferida), 0) as qty_conferida_total
from public.logistica_recebimentos r
left join public.logistica_recebimento_itens i on i.recebimento_id = r.id
group by r.id;

grant select on public.oraculo_recebimento_progress to authenticated;

comment on view public.oraculo_recebimento_progress is
  'Progresso de cada conferência de recebimento: itens totais, conferidos e divergentes, e unidades esperadas × conferidas. Fonte da lista em /logistica/recebimento.';
