create table if not exists public.oraculo_fiscal_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_key text not null,
  snapshot_label text not null,
  period_start date not null,
  period_end date not null,
  payload jsonb not null,
  captured_at timestamptz not null default now()
);

create index if not exists oraculo_fiscal_snapshots_key_captured_idx
  on public.oraculo_fiscal_snapshots (snapshot_key, captured_at desc, id desc);

create or replace view public.oraculo_fiscal_latest_snapshots as
select distinct on (snapshot_key)
  id,
  snapshot_key,
  snapshot_label,
  period_start,
  period_end,
  payload,
  captured_at
from public.oraculo_fiscal_snapshots
order by snapshot_key, captured_at desc, id desc;

alter table public.oraculo_fiscal_snapshots enable row level security;

revoke all on table public.oraculo_fiscal_snapshots from public, anon, authenticated;
revoke all on table public.oraculo_fiscal_latest_snapshots from public, anon, authenticated;
grant all on table public.oraculo_fiscal_snapshots to service_role;
grant select on table public.oraculo_fiscal_latest_snapshots to service_role;

insert into public.oraculo_fiscal_snapshots (
  snapshot_key,
  snapshot_label,
  period_start,
  period_end,
  payload
)
select
  'fiscal_dashboard',
  'Fiscal dashboard exclusions',
  date '2026-06-01',
  date '2026-06-19',
  jsonb_build_object(
    'linked_orders_count', 71191,
    'excluded_devolutions_count', 857,
    'excluded_devolutions_revenue', 1816353.97,
    'canceled_count', 89,
    'canceled_revenue', 1750174.08
  )
where not exists (
  select 1
  from public.oraculo_fiscal_snapshots
  where snapshot_key = 'fiscal_dashboard'
    and period_start = date '2026-06-01'
    and period_end = date '2026-06-19'
);

insert into public.oraculo_fiscal_snapshots (
  snapshot_key,
  snapshot_label,
  period_start,
  period_end,
  payload
)
select
  'sku_coverage',
  'SKU coverage snapshot',
  date '2026-06-01',
  date '2026-06-19',
  jsonb_build_object(
    'total_valid_invoices', 71198,
    'total_valid_revenue', 5243715.76,
    'invoices_with_matched_order', 71191,
    'invoices_with_order_items', 30987,
    'revenue_with_order_items', 2198329.66,
    'invoices_without_order_items', 40211,
    'revenue_without_order_items', 3045386.10,
    'order_link_invoice_pct', 99.99,
    'order_items_invoice_pct', 43.52,
    'order_items_revenue_pct', 41.92,
    'missing_order_items_revenue_pct', 58.08,
    'distinct_order_item_skus', 376
  )
where not exists (
  select 1
  from public.oraculo_fiscal_snapshots
  where snapshot_key = 'sku_coverage'
    and period_start = date '2026-06-01'
    and period_end = date '2026-06-19'
);
